spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/crud
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update

rest:
  branch-api:
    url: http://localhost:8001/api/v1/branches/